---
- name: Playbook to deploy flask bolierplate in production environment
  hosts: 127.0.0.1
  connection: local
  
  vars:
    application_user: ''
    application_group: ''
    application_path: ''

    # Gunicorn configuration
    gunicorn_workers: 1
    gunicorn_worker_connections: '500'
    gunicorn_bind: '127.0.0.1:5000'
    gunicorn_timeout: 120
    gunicorn_accesslog: 'access.log'
    gunicorn_errorlog: 'error.log'
    gunicorn_loglevel: 'info'

  tasks:
  - name: Install SO dependecies
    package:
      name:
        - python3-dev
        - python3-venv
        - build-essential
        - nodejs
        - npm
      state: present

  - name: Create Application Group
    group:
      name: '{{ application_group }}'
      gid: 480

  - name: Create Application user
    user:
      name: '{{ application_user }}'
      comment: Application User
      group: '{{application_group}}'
      shell: /bin/bash
      state: present
      home: '{{ application_path }}/{{ application_user }}'

  - name: Create public_html directory
    file:
      path: '{{ application_path }}/{{ application_user }}/public_html'
      state: directory
      owner: '{{ application_user }}'
      group: '{{application_group}}'
      mode: 0755

  - name: Copy Application Source
    copy:
      src: ./app
      dest: '{{ application_path }}/{{ application_user }}/public_html/'
      remote_src: yes
      owner: '{{ application_user }}'
      group: '{{application_group}}'

  - name: Copy requirements.txt
    copy:
      src: ./requirements.txt
      dest: '{{ application_path }}/{{ application_user }}/public_html/'
      remote_src: yes
      owner: '{{ application_user }}'
      group: '{{application_group}}'

  - name: Copy WSGI
    copy:
      src: ./wsgi.py
      dest: '{{ application_path }}/{{ application_user }}/public_html/'
      remote_src: yes
      owner: '{{ application_user }}'
      group: '{{application_group}}'

  - name: Gunicorn config
    template:
      src: gunicorn_config.py.j2
      dest: '{{ application_path }}/{{ application_user }}/public_html/gunicorn_config.py'
      remote_src: yes
      owner: '{{ application_user }}'
      group: '{{application_group}}'

  - name: Configuration file
    copy:
      src: ./config.py
      dest: '{{ application_path }}/{{ application_user }}/public_html/'
      remote_src: yes
      owner: '{{ application_user }}'
      group: '{{application_group}}'

  - name: .env file
    copy:
      dest: '{{ application_path }}/{{ application_user }}/public_html/.env'
      owner: '{{ application_user }}'
      group: '{{application_group}}'
      no_log: true
      content: |
        FLASK_APP=opentraining
        FLASK_ENV=production
        FLASK_CONFIG_FILE=config.ProductionConfig
        SECRET_KEY={{ secret_key }} 

  - name: Create python virtualenv and install requirements
    pip:
      virtualenv_command: /usr/bin/python3 -m venv
      virtualenv: '{{ application_path }}/{{ application_user }}/public_html/env'
      requirements: '{{ application_path }}/{{ application_user }}/public_html/requirements.txt'